const AUTH_SET_TOKEN = '/auth/SET_TOKEN';
const AUTH_DISCARD_TOKEN = '/auth/DISCARD_TOKEN';
const AUTH_SET_USER = '/auth/SET_USER';
const AUTH_REQUEST = '/auth/SET_USER';
const REQUEST_TOKEN = 'REQUEST_TOKEN';
const RECIEVE_TOKEN = 'RECIEVE_TOKEN';
const EMAIL_FORM_CHANGE = 'EMAIL_FORM_CHANGE';
const PASSWORD_FORM_CHANGE = 'PASSWORD_FORM_CHANGE';
const SUCCESSFUL_LOGIN = '/home';

export default {
	AUTH_SET_TOKEN,
	AUTH_DISCARD_TOKEN,
	AUTH_SET_USER, 
	AUTH_REQUEST,
	REQUEST_TOKEN,
	RECIEVE_TOKEN, 
	EMAIL_FORM_CHANGE,
	PASSWORD_FORM_CHANGE,
	SUCCESSFUL_LOGIN
}