const VIEW_STUDENT_LEVEL_FEEDBACK_GENERATOR = 'STUDENT_LEVEL_FEEDBACK_GENERATOR';
const GENERATE_STUDENT_LEVEL_FEEDBACK = 'GENERATE_STUDENT_LEVEL_FEEDBACK';


export default {
	VIEW_STUDENT_LEVEL_FEEDBACK_GENERATOR,
	GENERATE_STUDENT_LEVEL_FEEDBACK
}