const GET_MCM_TOPICS = 'GET_MCM_TOPICS';
const INVALIDATE_MCM_TOPICS = 'INVALIDATE_MCM_TOPICS';
const REQUEST_MCM_TOPICS = 'REQUEST_MCM_TOPICS';
const RECEIVE_MCM_TOPICS = 'RECEIVE_MCM_TOPICS';

export default {
	GET_MCM_TOPICS,
	INVALIDATE_MCM_TOPICS,
	REQUEST_MCM_TOPICS,
	RECEIVE_MCM_TOPICS
}