const GET_STUDENT_LEVELS = 'GET_STUDENT_LEVELS';
const INVALIDATE_STUDENT_LEVELS = 'INVALIDATE_STUDENT_LEVELS';
const REQUEST_STUDENT_LEVELS = 'REQUEST_STUDENT_LEVELS';
const RECEIVE_STUDENT_LEVELS = 'RECEIVE_STUDENT_LEVELS';

export default {
	GET_STUDENT_LEVELS,
	INVALIDATE_STUDENT_LEVELS,
	REQUEST_STUDENT_LEVELS,
	RECEIVE_STUDENT_LEVELS
}