const ADD_SENTENCE_SCORE = 'ADD_SENTENCE_SCORE'
const REMOVE_SENTENCE_SCORE = 'REMOVE_SENTENCE_SCORE'
const UPDATE_SENTENCE_SCORE = 'UPDATE_SENTENCE_SCORE'

export default {
	ADD_SENTENCE_SCORE,
	REMOVE_SENTENCE_SCORE,
	UPDATE_SENTENCE_SCORE
}