//MCM Topics
const ADD_SENTENCE_SCORE = 'ADD_SENTENCE_SCORE'
const REMOVE_SENTENCE_SCORE = 'REMOVE_SENTENCE_SCORE'
const UPDATE_SENTENCE_SCORE = 'UPDATE_SENTENCE_SCORE'
const UPDATE_MCM_TOPIC_NAME = 'UPDATE_MCM_TOPIC_NAME'

//Student Levels
const ADD_RANDOM_SENTENCE = 'ADD_RANDOM_SENTENCE'
const REMOVE_RANDOM_SENTENCE = 'REMOVE_RANDOM_SENTENCE'
const UPDATE_RANDOM_SENTENCE = 'UPDATE_RANDOM_SENTENCE'
const UPDATE_STUDENT_LEVEL_NAME = 'UPDATE_STUDENT_LEVEL_NAME'
const UPDATE_STUDENT_LEVEL_TEXT = 'UPDATE_STUDENT_LEVEL_TEXT'

export default {
	ADD_SENTENCE_SCORE,
	REMOVE_SENTENCE_SCORE,
	UPDATE_SENTENCE_SCORE,
	ADD_RANDOM_SENTENCE,
	REMOVE_RANDOM_SENTENCE,
	UPDATE_RANDOM_SENTENCE,
	UPDATE_MCM_TOPIC_NAME,
	UPDATE_STUDENT_LEVEL_NAME,
	UPDATE_STUDENT_LEVEL_TEXT
}