const GET_STUDENT_LEVEL = 'GET_STUDENT_LEVEL';
const INVALIDATE_STUDENT_LEVEL = 'INVALIDATE_STUDENT_LEVEL';
const REQUEST_STUDENT_LEVEL = 'REQUEST_STUDENT_LEVEL';
const RECEIVE_STUDENT_LEVEL = 'RECEIVE_STUDENT_LEVEL';
const UPDATE_STUDENT_LEVEL = 'UPDATE_STUDENT_LEVEL'

export default {
	GET_STUDENT_LEVEL,
	INVALIDATE_STUDENT_LEVEL,
	REQUEST_STUDENT_LEVEL,
	RECEIVE_STUDENT_LEVEL,
	UPDATE_STUDENT_LEVEL
}