const GET_MCM_TOPIC_EDIT = 'GET_MCM_TOPIC_EDIT';
const INVALIDATE_MCM_TOPIC_EDIT = 'INVALIDATE_MCM_TOPIC_EDIT';
const REQUEST_MCM_TOPIC_EDIT = 'REQUEST_MCM_TOPIC_EDIT';
const RECEIVE_MCM_TOPIC_EDIT = 'RECEIVE_MCM_TOPIC_EDIT';
const ADD_SENTENCE_SCORE = 'ADD_SENTENCE_SCORE'
const REMOVE_SENTENCE_SCORE = 'REMOVE_SENTENCE_SCORE'
const UPDATE_SENTENCE_SCORE = 'UPDATE_SENTENCE_SCORE'
const UPDATE_MCM_TOPIC_EDIT = 'UPDATE_MCM_TOPIC_EDIT'

export default {
	GET_MCM_TOPIC_EDIT,
	INVALIDATE_MCM_TOPIC_EDIT,
	REQUEST_MCM_TOPIC_EDIT,
	RECEIVE_MCM_TOPIC_EDIT,
	ADD_SENTENCE_SCORE,
	REMOVE_SENTENCE_SCORE,
	UPDATE_SENTENCE_SCORE,
	UPDATE_MCM_TOPIC_EDIT
}